import { Router } from 'express';
import fs from 'node:fs';
import path from 'node:path';
import { crawlFileTree } from '../scanner/fileTree.js';
import { readDependencies, readPythonDependencies } from '../scanner/dependencies.js';
import { parseImports } from '../scanner/imports.js';
import { detectFrameworks } from '../scanner/frameworks.js';
import { extractDbSchema } from '../scanner/dbSchema.js';
import { gatherSources } from '../scanner/sources.js';
import { askClaudeJSON } from '../lib/anthropic.js';

function handle(fn) {
  return async (req, res) => {
    try {
      await fn(req, res);
    } catch (err) {
      console.error(err);
      res.status(500).json({ error: err.message, raw: err.raw });
    }
  };
}

/**
 * Write a compact `.lore/map.md` from the produced graph so the builder (and
 * the user's own Claude Code) can read it to locate which files a change
 * concerns — instead of reading the whole codebase. Deterministic, no AI.
 */
function writeMapFile(root, graph) {
  try {
    const lines = [
      '# Lore architecture map',
      '',
      '_Generated by Lore. Use this to find which files/areas a change concerns before reading code._',
      '',
    ];
    const render = (nodes, depth) => {
      for (const n of nodes || []) {
        const pad = '  '.repeat(depth);
        const tag = n.detailType ? ` [${n.detailType}]` : '';
        const note = n.notes ? ` — ${n.notes}` : '';
        lines.push(`${pad}- ${n.title}${tag}${note}`);
        if (n.children?.nodes?.length) render(n.children.nodes, depth + 1);
      }
    };
    render(graph.nodes, 0);
    const dir = path.join(root, '.lore');
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'map.md'), lines.join('\n') + '\n', 'utf8');
  } catch {
    /* non-fatal — the map file is an optimization */
  }
}

/** Gather a structured scan summary of the project for the AI. */
export async function gatherScan(root, { full = true } = {}) {
  const tree = await crawlFileTree(root);
  const deps = readDependencies(root);
  const python = readPythonDependencies(root);
  const frameworks = detectFrameworks(root, deps);
  const imports = full ? parseImports(root, tree.files) : { graph: [], externalCounts: {} };

  return { tree, deps, python, frameworks, imports };
}

/** Compact the scan into a token-friendly string for Claude. */
export function summarize(scan) {
  const { tree, deps, python, frameworks, imports } = scan;
  const lines = [];
  lines.push(`File count: ${tree.fileCount}`);
  lines.push(`Extensions: ${JSON.stringify(tree.extensions)}`);
  lines.push('\nFile tree:\n' + tree.tree);
  if (deps.hasPackageJson) {
    lines.push(`\npackage.json name: ${deps.name || '(none)'}`);
    lines.push(`Scripts: ${JSON.stringify(deps.scripts)}`);
    lines.push(`Dependencies: ${Object.keys(deps.dependencies).join(', ')}`);
    lines.push(`Dev dependencies: ${Object.keys(deps.devDependencies).join(', ')}`);
  }
  if (python) lines.push(`\nPython: ${JSON.stringify(python).slice(0, 1500)}`);
  lines.push(`\nDetected frameworks: ${frameworks.frameworks.join(', ') || 'none'}`);
  lines.push(`Schema files: ${frameworks.schemaFiles.join(', ') || 'none'}`);
  lines.push(`Env keys (names only): ${frameworks.envKeys.join(', ') || 'none'}`);
  if (imports.graph.length) {
    const top = Object.entries(imports.externalCounts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 30)
      .map(([k, v]) => `${k}(${v})`)
      .join(', ');
    lines.push(`\nMost-imported external packages: ${top}`);
  }
  return lines.join('\n');
}

// Fixed vocabulary for top-level nodes. Using exact titles keeps the map
// consistent across repeated scans — no creative renaming each run.
const TOP_LEVEL_TITLES = [
  'Frontend', 'Backend', 'Database', 'Auth', 'Integrations', 'Infrastructure', 'CLI',
];

const GRAPH_SYSTEM = [
  'You are the reverse-engineering engine for Lore Map.',
  'Given a structured scan of an existing codebase, produce a node graph with FIXED top-level categories.',
  '',
  'STRICT RULE — top-level node titles must be EXACTLY one of:',
  TOP_LEVEL_TITLES.join(', '),
  'No other titles are allowed. No creative names. No framework names in the title.',
  'Put frameworks/libraries in the "stack" array instead.',
  'Only include categories that actually exist in the project (3-6 nodes max).',
  '',
  'Output JSON shaped exactly as:',
  '{',
  '  "summary": "2-3 sentence plain description of what this project does",',
  '  "nodes": [{ "title": "Backend", "type": "core", "stack": ["Express","Node"], "notes": "REST API, handles auth and business logic" }],',
  '  "edges": [{ "from": "Backend", "to": "Database", "label": "reads/writes" }]',
  '}',
  'Output ONLY the JSON object.',
].join('\n');

const GRAPH_DEEP_SYSTEM = [
  'You are the deep reverse-engineering engine for Lore Map.',
  'You receive a scan PLUS the actual source code. Produce a NESTED graph: fixed top-level blocks with real internals as children.',
  '',
  'STRICT RULE — top-level node titles must be EXACTLY one of:',
  TOP_LEVEL_TITLES.join(', '),
  'No other titles. No framework names in the title (put them in "stack"). 3-6 top-level nodes max.',
  'This rule ensures the map looks the same every time the user rescans.',
  '',
  'Rules for children (internals):',
  '- Database: one child per table/model (detailType "table"), notes = key fields. Edges = relations.',
  '- Backend/Frontend/other code: one child per key file or module (detailType "module"),',
  '  notes = its main responsibility in one phrase. Edges = imports/calls.',
  '- Base ONLY on actual code shown. Do not invent files, tables, or relations.',
  '- Max ~15 children per block; group minor files rather than listing every one.',
  '- Notes are one short phrase, not sentences.',
  '',
  'Output JSON shaped exactly as:',
  '{',
  '  "summary": "2-3 sentence plain description of what this project does",',
  '  "nodes": [{',
  '    "title": "Database", "type": "core", "detailType": "database", "stack": ["Postgres"],',
  '    "notes": "primary data store",',
  '    "children": {',
  '      "nodes": [{ "title": "User", "type": "custom", "detailType": "table", "notes": "id, email, created_at" }],',
  '      "edges": [{ "from": "User", "to": "Post", "label": "has many" }]',
  '    }',
  '  }],',
  '  "edges": [{ "from": "Backend", "to": "Database", "label": "reads/writes" }]',
  '}',
  'Output ONLY the JSON object.',
].join('\n');

export function createScanRouter(ctx) {
  const router = Router();

  // Full scan → node graph.
  router.post(
    '/',
    handle(async (_req, res) => {
      const scan = await gatherScan(ctx.projectRoot, { full: true });
      const summary = summarize(scan);
      const graph = await askClaudeJSON(GRAPH_SYSTEM, `Scan summary:\n${summary}`);
      writeMapFile(ctx.projectRoot, graph);
      res.json({ scanSummary: summary, ...graph });
    })
  );

  // Deep scan: parse DB schema + code structure deterministically, then have
  // the AI assemble a NESTED graph (blocks with real internals as children).
  router.post(
    '/deep',
    handle(async (_req, res) => {
      const scan = await gatherScan(ctx.projectRoot, { full: true });
      const db = await extractDbSchema(ctx.projectRoot);
      // Feed the AI the ACTUAL source (any language), budgeted for big repos.
      const sources = gatherSources(ctx.projectRoot, scan.tree.files);

      const summary =
        summarize(scan) +
        `\n\n=== SOURCE FILES (${sources.includedCount}/${sources.totalCount}` +
        `${sources.omittedCount ? `, ${sources.omittedCount} omitted for size` : ''}) ===\n` +
        sources.text;
      const graph = await askClaudeJSON(GRAPH_DEEP_SYSTEM, `Deep scan:\n${summary}`, { maxTokens: 32000 });

      // If a Prisma/SQL schema was present, overwrite the DB block's children
      // with the exact parsed tables/relations (free, exact). Other languages
      // (Python models, etc.) are handled by the AI reading the source above.
      if (db.tables.length) {
        const children = {
          nodes: db.tables.map((t) => ({
            title: t.name,
            type: 'custom',
            detailType: 'table',
            fields: t.fields.map((f) => ({ name: f.name, type: f.type, rel: f.refTable })),
            notes: t.fields.map((f) => f.name).join(', '),
          })),
          edges: db.relations.map((r) => ({ from: r.from, to: r.to, label: r.label })),
        };
        graph.nodes = graph.nodes || [];
        const dbNode = graph.nodes.find((n) => n.detailType === 'database');
        if (dbNode) dbNode.children = children;
        else graph.nodes.push({ title: 'Database', type: 'core', detailType: 'database', notes: `${db.tables.length} tables`, children });
      }

      writeMapFile(ctx.projectRoot, graph);
      res.json({
        scanSummary: summary,
        parsed: {
          tableCount: db.tables.length,
          relationCount: db.relations.length,
          filesRead: sources.includedCount,
          filesTotal: sources.totalCount,
          omitted: sources.omittedCount,
        },
        ...graph,
      });
    })
  );

  // Sync: light scan diffed against the existing lore.md, returns patch suggestions.
  router.post(
    '/sync',
    handle(async (_req, res) => {
      const lorePath = path.join(ctx.projectRoot, 'lore.md');
      if (!fs.existsSync(lorePath)) {
        return res.status(400).json({ error: 'No lore.md found to sync against. Run a scan or plan first.' });
      }
      const existing = fs.readFileSync(lorePath, 'utf8');
      const scan = await gatherScan(ctx.projectRoot, { full: false });
      const summary = summarize(scan);

      const system = [
        'You are the sync engine for Lore Map.',
        'Compare the existing lore.md blueprint against a fresh lightweight scan of the codebase.',
        'Identify ONLY what changed: new nodes, removed nodes, or stack/dependency shifts.',
        'Be surgical — do not rewrite unchanged parts.',
        'Output JSON shaped exactly as:',
        '{ "patches": [{ "node": "title or NEW", "change": "added|removed|modified", "detail": "what changed and the suggested edit" }] }',
      ].join('\n');

      const user = `Existing lore.md:\n${existing}\n\n---\n\nFresh scan summary:\n${summary}`;
      const data = await askClaudeJSON(system, user);
      res.json(data);
    })
  );

  return router;
}
